# Generated by Django 5.1.4 on 2026-06-01 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareasset',
            name='acceptance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='acceptance_status',
            field=models.CharField(choices=[('none', 'Not Required'), ('pending', 'Pending User Acceptance'), ('accepted', 'Accepted by User'), ('rejected', 'Rejected by User')], db_index=True, default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='acceptance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
