# Generated by Django 5.1.4 on 2026-06-02 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('current', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'problem_counter',
            },
        ),
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('workaround', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('known_error', 'Known Error'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('linked_tickets', models.ManyToManyField(blank=True, related_name='problems', to='tickets.ticket')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
