# Generated by Django 5.1.4 on 2026-06-03 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('ticket_created', 'When a ticket is created'), ('ticket_updated', 'When a ticket is updated')], db_index=True, default='ticket_created', max_length=30)),
                ('conditions', models.JSONField(default=list)),
                ('condition_match', models.CharField(choices=[('all', 'All conditions (AND)'), ('any', 'Any condition (OR)')], default='all', max_length=5)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('run_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers run first')),
                ('times_triggered', models.PositiveIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_rule',
                'ordering': ['run_order', 'created_at'],
            },
        ),
    ]
