# Generated by Django 5.1.4 on 2026-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('section', models.CharField(choices=[('smtp', 'Email (SMTP)'), ('imap', 'Email Inbound (IMAP)'), ('teams', 'Microsoft Teams'), ('general', 'General')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'system_config',
                'ordering': ['section', 'display_order'],
            },
        ),
    ]
