# Generated by Django 5.1.4 on 2026-06-02 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_hardwareasset_acceptance_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('devices_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discovery_scan',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('os_info', models.CharField(blank=True, max_length=300)),
                ('open_ports', models.JSONField(default=list)),
                ('snmp_info', models.JSONField(default=dict)),
                ('ssh_info', models.JSONField(default=dict)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New — not in inventory'), ('matched', 'Matched existing asset'), ('imported', 'Imported to inventory'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=15)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('matched_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_matches', to='assets.hardwareasset')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='discovery.discoveryscan')),
            ],
            options={
                'db_table': 'discovery_device',
                'ordering': ['ip_address'],
            },
        ),
    ]
