# Generated by Django 5.1.4 on 2026-06-02 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('current', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_sr_counter',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('form_fields', models.JSONField(default=list)),
                ('fulfillment_sla_hours', models.PositiveIntegerField(default=72)),
                ('auto_create_ticket', models.BooleanField(default=True)),
                ('requires_manager_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.catalogcategory')),
            ],
            options={
                'db_table': 'catalog_item',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('form_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.catalogitem')),
                ('linked_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='tickets.ticket')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_service_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
