# Generated by Django 5.1.4 on 2026-06-02 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_add_resolution_notes_sla_pause_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=4)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('use_ssl', models.BooleanField(default=True)),
                ('imap_folder', models.CharField(default='INBOX', max_length=200)),
                ('processed_folder', models.CharField(default='INBOX.Processed', help_text='IMAP folder to move processed emails into. Ignored for POP3.', max_length=200)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('emails_processed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, help_text='Tickets created from this mailbox get this category by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_mailboxes', to='tickets.category')),
            ],
            options={
                'db_table': 'email_config_inbound_mailbox',
                'ordering': ['name'],
            },
        ),
    ]
