# Generated by Django 5.1.4 on 2026-06-01 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('license_type', models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('oem', 'OEM'), ('freeware', 'Freeware'), ('open_source', 'Open Source')], db_index=True, default='perpetual', max_length=20)),
                ('license_key', models.TextField(blank=True)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'software_license',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seats_requested', models.PositiveIntegerField()),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seat_requests', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='software.softwarelicense')),
            ],
            options={
                'db_table': 'software_seat_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('seat_count_changed', 'Seat Count Changed'), ('expiry_renewed', 'Subscription Renewed'), ('expiry_changed', 'Expiry Date Changed'), ('installation_added', 'Installation Added'), ('installation_removed', 'Installation Removed'), ('status_changed', 'Status Changed'), ('license_created', 'License Created'), ('seat_requested', 'Additional Seats Requested')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='software.softwarelicense')),
            ],
            options={
                'db_table': 'software_license_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_installations', to='assets.hardwareasset')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_installations', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='software.softwarelicense')),
            ],
            options={
                'db_table': 'software_installation',
                'ordering': ['-created_at'],
                'unique_together': {('license', 'hardware_asset')},
            },
        ),
    ]
