# Generated by Django 5.1.4 on 2026-06-01 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwareinstallation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_user_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='hardware_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_installations', to='assets.hardwareasset'),
        ),
    ]
