# Generated by Django 5.1.4 on 2026-06-01 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('software', '0002_alter_softwareinstallation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='softwareinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('hardware_asset__isnull', False)), fields=('license', 'hardware_asset'), name='unique_license_per_hardware'),
        ),
        migrations.AddConstraint(
            model_name='softwareinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_user__isnull', False), ('hardware_asset__isnull', True)), fields=('license', 'assigned_user'), name='unique_license_per_user'),
        ),
    ]
