# Generated by Django 5.1.4 on 2026-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('tickets', 'Tickets'), ('hardware_assets', 'Hardware Assets'), ('software_assets', 'Software Assets')], db_index=True, max_length=30)),
                ('category_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date & Time'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi-Select'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('email', 'Email')], max_length=15)),
                ('options', models.JSONField(blank=True, default=list)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_field_schema',
                'ordering': ['module', 'display_order', 'label'],
                'unique_together': {('module', 'name', 'category_id')},
            },
        ),
    ]
